version: '3.7'

services:

  sample-prod:
    container_name: chronos-web-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1537:80'
networks:
  frontend:
    driver: nginxproxymanager_default
